steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/catalyst-be/catalyst-main/embed-api:$COMMIT_SHA'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/catalyst-be/catalyst-main/embed-api:$COMMIT_SHA'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      [
        "run","deploy","embed-api",
        "--image=us-central1-docker.pkg.dev/catalyst-be/catalyst-main/embed-api:$COMMIT_SHA",
        "--region=us-central1",
        "--platform=managed",

      
        "--cpu=2",
        "--memory=4Gi",
        "--concurrency=80",
        "--timeout=1200",
        "--min-instances=0",
        "--max-instances=5",
        "--port=8080",

        "--no-allow-unauthenticated",
        "--set-env-vars=TORCH_NUM_THREADS=4",
        "--set-env-vars=EMBED_MODEL=sentence-transformers/all-MiniLM-L6-v2",
        "--set-env-vars=UVICORN_WORKERS=1"
      ]

images:
  - 'us-central1-docker.pkg.dev/catalyst-be/catalyst-main/embed-api:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY

